/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Lock } from "./Lock";
export type { MedicalRecords } from "./MedicalRecords";
export * as factories from "./factories";
export { Lock__factory } from "./factories/Lock__factory";
export { MedicalRecords__factory } from "./factories/MedicalRecords__factory";
