/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace MedicalRecords {
  export type RecordStruct = {
    patientId: string;
    dataHash: string;
    doctor: AddressLike;
    timestamp: BigNumberish;
  };

  export type RecordStructOutput = [
    patientId: string,
    dataHash: string,
    doctor: string,
    timestamp: bigint
  ] & {
    patientId: string;
    dataHash: string;
    doctor: string;
    timestamp: bigint;
  };
}

export interface MedicalRecordsInterface extends Interface {
  getFunction(nameOrSignature: "addRecord" | "getRecords"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "RecordAdded"): EventFragment;

  encodeFunctionData(
    functionFragment: "addRecord",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "getRecords", values: [string]): string;

  decodeFunctionResult(functionFragment: "addRecord", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getRecords", data: BytesLike): Result;
}

export namespace RecordAddedEvent {
  export type InputTuple = [
    patientId: string,
    doctor: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    patientId: string,
    doctor: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    patientId: string;
    doctor: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MedicalRecords extends BaseContract {
  connect(runner?: ContractRunner | null): MedicalRecords;
  waitForDeployment(): Promise<this>;

  interface: MedicalRecordsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addRecord: TypedContractMethod<
    [_patientId: string, _dataHash: string],
    [void],
    "nonpayable"
  >;

  getRecords: TypedContractMethod<
    [_patientId: string],
    [MedicalRecords.RecordStructOutput[]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addRecord"
  ): TypedContractMethod<
    [_patientId: string, _dataHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getRecords"
  ): TypedContractMethod<
    [_patientId: string],
    [MedicalRecords.RecordStructOutput[]],
    "view"
  >;

  getEvent(
    key: "RecordAdded"
  ): TypedContractEvent<
    RecordAddedEvent.InputTuple,
    RecordAddedEvent.OutputTuple,
    RecordAddedEvent.OutputObject
  >;

  filters: {
    "RecordAdded(string,address,uint256)": TypedContractEvent<
      RecordAddedEvent.InputTuple,
      RecordAddedEvent.OutputTuple,
      RecordAddedEvent.OutputObject
    >;
    RecordAdded: TypedContractEvent<
      RecordAddedEvent.InputTuple,
      RecordAddedEvent.OutputTuple,
      RecordAddedEvent.OutputObject
    >;
  };
}
